version: '3.8'

services:
  instagram-collector:
    build: .
    environment:
      - MONGO_CONNECTION_STRING=${MONGO_CONNECTION_STRING}
      - MONGO_DB=${MONGO_DB}
      - MONGO_COLLECTION=${MONGO_COLLECTION}
      - API_ROUTE=${API_ROUTE}
      - SECRET_TOKEN=${SECRET_TOKEN}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped